# Generated by Django 2.2.1 on 2019-05-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form_app', '0002_auto_20190523_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulaire',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='formulaire',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
