# Generated by Django 2.2.1 on 2019-05-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_auto_20190528_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='manager',
        ),
    ]
